### ISSUE TITLE
rdf:HTML and rdfXMLLiteral datatypes

### ISSUE THREAD

**Issue by ktk** [fusepool/fusepool-uduvudu#2]
We need proper support for rdf:HTML and rdf:XMLLiteral RDF 1.1 datatypes, see http://www.w3.org/TR/rdf11-concepts/#section-Datatypes

It might be smart to check if at least the XMLLiteral is valid XML. Might completely break the output if not. HTML is more resilient.

**Comment by l00mi** [comment]
Closing, fusepool-uduvudu for comments, please use https://github.com/uduvudu/uduvudu.
