### ISSUE TITLE
subject with labels

### ISSUE THREAD

**Issue by moissinac** [fusepool/fusepool-uduvudu#4]
Your samples suppose some simple relations with literals
In my data, I have some classes with links (by predicate) and each object has his own label
For simplified example:
theme22 hasSubject subject12
subject12 hasTopic topic35
topic35 rdfs:label "Fribourg"@fr
subject12 hasRole role75
role75 rdfs:topic "study"
theme22 rdfs:label "Study of the map of Fribourg"
 
The only predicate which address literals is rdfs:label
I'm searching how to define matchers and templates to display a theme and can't find how to

**Comment by l00mi** [comment]
Please be noted that this version of Uduvudu is not anymore maintained. Please use https://github.com/uduvudu/uduvudu for an updated version!
There you find also some basic info about the use of the matchers: https://github.com/uduvudu/uduvudu/blob/master/doc/matcher.md

HTH

**Comment by l00mi** [comment]
If any other questions arise ... please open a ticket over there.
